### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by ScottHutchinson** [Zaid-Ajaj/tabula-rasa#4]
I tried to login as "admin", but it returns `UsernameDoesNotExist`.

How do I know what credentials to use?

Where is the database? I searched for *.db, but found nothing.

I assume once I can login as an admin, then it will be obvious how to add other logins.

**Comment by Nhowka** [comment]
guest/guest

It's defined here: https://github.com/Zaid-Ajaj/tabula-rasa/blob/master/Server/Admin.fs#L29-L39
And created here: https://github.com/Zaid-Ajaj/tabula-rasa/blob/master/Server/WebApp.fs#L17

**Comment by ScottHutchinson** [comment]
@Nhowka Thanks. And I found the .db file in my AppData\Roaming\tabula-rasa folder.

So far, I don't see a way to add another login, but I guess maybe the app is just for one person's blog, which is fine.

**Comment by Zaid-Ajaj** [comment]
@ScottHutchinson Indeed, there is one admin user now, I wanted to add more types of users that can login and write comments but unfortunately didn't have the time to that :( 

I will soon add login instructions to the docs. 

The database location is always the [application data directory](https://github.com/Zaid-Ajaj/tabula-rasa/blob/master/Server/Environment.fs#L9) of your system You can also browse the data inside the database using one of the GUI's for LiteDb, [LiteDbExplorer](https://github.com/JosefNemec/LiteDbExplorer) is my favorite 👌 

And if you want, you can run the application using an in-memory database (LiteDB built-in) by adding and running this target:
```fs
Target "WatchInMemory" <| fun () ->
  [ async { run dotnet "watch run --store in-memory" "Server" }; 
    async { run dotnet "fable npm-run start" ("Client" </> "src") } ]
  |> Async.Parallel
  |> Async.RunSynchronously
  |> ignore
```

**Comment by Zaid-Ajaj** [comment]
I assume this can be closed, please reopen if you still have problems with logging in :smile:
